export interface ComponentThemeMeta {
  label: string;
  tokens: Array<{
    var: string; // CSS 变量名
    label: string; // 易读中文描述
  }>;
}

/**
 * 组件-Token 映射表
 * 我们已剔除大量自动生成的无用变量名，将依然在真实代码中引用的 token 进行科学分类。
 */
export const componentTokenMap: Record<string, ComponentThemeMeta> = {
  // ====================================================
  // === System Semantic Colors (全局生效) ===
  // ====================================================
  'sys-colors': {
    label: "系统语义色",
    tokens: [
      // 背景语义
      { var: "--sys-bg-base", label: "全局-背景-基础", labelEn: "Base background (darkest)" },
      { var: "--sys-bg-surface", label: "全局-背景-表面", labelEn: "Surface background (sidebar/panel)" },
      { var: "--sys-bg-elevated", label: "全局-背景-抬升", labelEn: "Elevated background (titlebar)" },
      { var: "--sys-bg-overlay", label: "全局-背景-浮层", labelEn: "Overlay background (popup/menu)" },
      { var: "--sys-bg-hover", label: "全局-背景-悬停", labelEn: "Global hover background" },
      { var: "--sys-bg-active", label: "全局-背景-激活", labelEn: "Global active background" },
      // 文本语义
      { var: "--sys-text-primary", label: "全局-文本-主要", labelEn: "Primary text color" },
      { var: "--sys-text-secondary", label: "全局-文本-次要", labelEn: "Secondary text color" },
      { var: "--sys-text-muted", label: "全局-文本-弱化", labelEn: "Muted text color" },
      { var: "--sys-text-inverse", label: "全局-文本-反色", labelEn: "Inverse text (on light buttons)" },
      // 边框语义
      { var: "--sys-border-base", label: "全局-边框-基础", labelEn: "Global base border" },
      { var: "--sys-border-divider", label: "全局-边框-分隔线", labelEn: "Global divider" },
      // 品牌色
      { var: "--sys-color-primary", label: "全局-颜色-主要", labelEn: "Global accent / brand color" },
      { var: "--accent-color", label: "强调-颜色", labelEn: "Accent color (selection/indicator)" },
      { var: "--focus-border-color", label: "焦点-边框-颜色", labelEn: "Focus border color" },
      // 顶层布局兼容色
      { var: "--app-background", label: "全局-背景", labelEn: "App global background" },
      { var: "--app-foreground", label: "全局-文本", labelEn: "App global foreground" },
      { var: "--editor-background", label: "编辑器-背景", labelEn: "Editor / content area background" },
      { var: "--sidebar-background", label: "侧栏-背景", labelEn: "Sidebar background" },
      { var: "--activitybar-background", label: "活动栏-背景", labelEn: "Activity bar background" },
      { var: "--statusbar-background", label: "状态栏-背景", labelEn: "Status bar background" },
      { var: "--titlebar-background", label: "标题栏-背景", labelEn: "Title bar background" },
      { var: "--panel-background", label: "面板-背景", labelEn: "Panel background" },
      { var: "--widget-background", label: "组件-背景", labelEn: "Widget background" },
      // 全局交互色
      { var: "--border-color", label: "边框-颜色", labelEn: "Global border color" },
      { var: "--widget-border-color", label: "组件-边框-颜色", labelEn: "Widget border color" },
      { var: "--hover-background", label: "悬停-背景", labelEn: "Hover background" },
      { var: "--selection-background", label: "选区-背景", labelEn: "Selection background" },
    ],
  },
  // ====================================================
  // === Layout Components ===
  // ====================================================
  titlebar: {
    label: "标题栏",
    labelEn: "Title Bar",
    tokens: [
      { var: "--titlebar-background", label: "标题栏-背景", labelEn: "Title bar background" },
      { var: "--st-titlebar-text", label: "标题栏-文本", labelEn: "Text color" },
      { var: "--st-titlebar-icon", label: "标题栏-图标", labelEn: "Icon color" },
      { var: "--st-titlebar-hover-bg", label: "标题栏-悬停-背景", labelEn: "Titlebar-Button-Hover bg" },
      { var: "--st-titlebar-active-bg", label: "标题栏-激活-背景", labelEn: "Titlebar-Button-Active bg" },
      { var: "--st-titlebar-icon-hover", label: "标题栏-图标-悬停", labelEn: "Icon hover color" },
    ],
  },
  activitybar: {
    label: "活动栏",
    labelEn: "Activity Bar",
    tokens: [
      { var: "--activitybar-background", label: "活动栏-背景", labelEn: "Activity bar background" },
      { var: "--activitybar-inactive-foreground", label: "活动栏-inactive-文本", labelEn: "Inactive icon color" },
      { var: "--st-activitybar-icon-hover", label: "活动栏-图标-悬停", labelEn: "Icon hover color" },
      { var: "--st-activitybar-icon-active", label: "活动栏-图标-激活", labelEn: "Active icon color" },
      { var: "--activitybar-active-border", label: "活动栏-激活-边框", labelEn: "Active item highlight border" },
      { var: "--st-activitybar-menu-text", label: "活动栏-菜单-文本", labelEn: "Menu text color" },
    ],
  },
  sidebar: {
    label: "侧边栏",
    labelEn: "Sidebar Container",
    tokens: [
      { var: "--sidebar-background", label: "侧栏-背景", labelEn: "Sidebar background" },
      { var: "--st-sidebar-title-text", label: "侧栏-标题-文本", labelEn: "Title text color" },
      { var: "--st-sidebar-text", label: "侧栏-文本", labelEn: "Normal text color" },
      { var: "--st-sidebar-muted-text", label: "侧栏-弱化-文本", labelEn: "Muted text color" },
      { var: "--st-sidebar-action-hover", label: "侧栏-action-悬停", labelEn: "Action button hover" },
      { var: "--st-sidebar-panel-bg", label: "侧栏-面板-背景", labelEn: "Sub-panel background" },
      { var: "--st-panel-action-hover", label: "面板-action-悬停", labelEn: "Panel action hover" },
      { var: "--st-panel-header-text", label: "面板-头部-文本", labelEn: "Panel header text" },
      { var: "--st-panel-muted-text", label: "面板-弱化-文本", labelEn: "Panel muted text" },
      { var: "--st-popover-bg", label: "弹出框-背景", labelEn: "Popover background" },
      { var: "--st-popover-border", label: "弹出框-边框", labelEn: "Popover border" },
    ],
  },
  statusbar: {
    label: "状态栏",
    labelEn: "Status Bar",
    tokens: [
      { var: "--statusbar-background", label: "状态栏-背景", labelEn: "Status bar background" },
      { var: "--statusbar-debugging-background", label: "状态栏-调试-背景", labelEn: "Debugging mode background" },
      { var: "--st-statusbar-text", label: "状态栏-文本", labelEn: "Text color" },
      { var: "--st-statusbar-divider", label: "状态栏-分隔线", labelEn: "Divider color" },
      { var: "--st-statusbar-btn-bg", label: "状态栏-按钮-背景", labelEn: "Button area background" },
      { var: "--st-statusbar-btn-hover", label: "状态栏-按钮-悬停", labelEn: "Button hover background" },
      { var: "--st-statusbar-success-text", label: "状态栏-成功-文本", labelEn: "Update ready accent text" },
      { var: "--st-statusbar-icon", label: "状态栏-图标", labelEn: "Default icon color" },
      { var: "--statusbar-btn-hover", label: "状态栏-按钮-悬停", labelEn: "Button hover" },
      { var: "--statusbar-btn-text", label: "状态栏-按钮-文本", labelEn: "Button text" },
      { var: "--statusbar-icon", label: "状态栏-图标", labelEn: "Icon color" },
      { var: "--statusbar-success-text", label: "状态栏-成功-文本", labelEn: "Success accent text" },
    ],
  },
  "editor-area": {
    label: "编辑器区域",
    labelEn: "Editor Area",
    tokens: [
      { var: "--editor-area-bg", label: "编辑器-area-背景", labelEn: "Main area background" },
      { var: "--editor-area-tabs-bg", label: "编辑器-area-tabs-背景", labelEn: "Tab bar outer background" },
      { var: "--st-menu-bg", label: "菜单-背景", labelEn: "Menu background" },
      { var: "--editor-area-accent", label: "编辑器-area-强调", labelEn: "Editor area accent" },
      { var: "--editor-area-tab-border", label: "编辑器-area-标签页-边框", labelEn: "Tab border" },
      { var: "--editor-area-tab-text", label: "编辑器-area-标签页-文本", labelEn: "Tab text" },
    ],
  },
  "editor-tabs": {
    label: "编辑器标签页",
    labelEn: "Editor Tabs",
    tokens: [
      { var: "--st-editor-tabs-bg", label: "编辑器-tabs-背景", labelEn: "Tab bar background" },
      { var: "--st-tab-active-bg", label: "标签页-激活-背景", labelEn: "Active tab background" },
      { var: "--st-tab-inactive-bg", label: "标签页-inactive-背景", labelEn: "Inactive tab background" },
      { var: "--st-tab-active-text", label: "标签页-激活-文本", labelEn: "Active tab text" },
      { var: "--st-tab-inactive-text", label: "标签页-inactive-文本", labelEn: "Inactive tab text" },
      { var: "--st-tab-border", label: "标签页-边框", labelEn: "Tab right border" },
    ],
  },

  // ====================================================
  // === 会话列表 ===
  // ====================================================
  "session-list-sidebar": {
    label: "会话列表侧边栏",
    labelEn: "Session List Sidebar",
    tokens: [
      { var: "--session-list-sidebar-bg", label: "会话-列表-侧栏-背景", labelEn: "Sidebar background" },
      { var: "--session-list-sidebar-text", label: "会话-列表-侧栏-文本", labelEn: "Normal text color" },
      { var: "--session-list-sidebar-muted", label: "会话-列表-侧栏-弱化", labelEn: "Muted text color" },
      { var: "--session-list-sidebar-border", label: "会话-列表-侧栏-边框", labelEn: "Border color" },
      { var: "--session-list-sidebar-header-bg", label: "会话-列表-侧栏-头部-背景", labelEn: "Header background" },
    ],
  },
  "session-list-item": {
    label: "会话列表项卡片",
    labelEn: "Session List Item Card",
    tokens: [
      { var: "--st-list-item-bg", label: "列表-选项-背景", labelEn: "Item default background" },
      { var: "--session-item-hover-bg", label: "会话-选项-悬停-背景", labelEn: "Hover background" },
      { var: "--session-item-active-bg", label: "会话-选项-激活-背景", labelEn: "Active background" },
      { var: "--session-item-active-border", label: "会话-选项-激活-边框", labelEn: "Active left border" },
      { var: "--session-item-foreground", label: "会话-选项-文本", labelEn: "Text color" },
      { var: "--st-session-serial-text", label: "会话-串口-文本", labelEn: "Serial session text" },
    ],
  },

  // ====================================================
  // === 监视器 (Serial / MQTT / Terminal) ===
  // ====================================================
  "serial-monitor": {
    label: "串口监视器主区域",
    labelEn: "Serial Monitor Area",
    tokens: [
      { var: "--st-monitor-rx-bg", label: "监视器-RX-背景", labelEn: "RX area base background" },
      { var: "--st-monitor-log-bg", label: "监视器-log-背景", labelEn: "Monitor log layer background" },
      { var: "--st-toolbar-bg", label: "工具栏-背景", labelEn: "Top toolbar background" },
      { var: "--st-monitor-toolbar-border", label: "监视器-工具栏-边框", labelEn: "Toolbar border" },
      { var: "--st-monitor-toolbar-foreground", label: "监视器-工具栏-文本", labelEn: "Toolbar text" },

      // 各种过滤/视图/设置按钮
      { var: "--st-serial-filter-group-bg", label: "串口-过滤-group-背景", labelEn: "Filter group background" },
      { var: "--st-serial-filter-group-border", label: "串口-过滤-group-边框", labelEn: "Filter group border" },
      { var: "--st-serial-filter-group-divider", label: "串口-过滤-group-分隔线", labelEn: "Filter group divider" },
      { var: "--st-serial-btn-filter-tx-bg", label: "串口-按钮-过滤-TX-背景", labelEn: "TX filter button bg" },
      {
        var: "--st-serial-btn-filter-tx-active-bg",
        label: "过滤TX按钮激活态背景",
        labelEn: "TX filter active bg",
      },
      { var: "--st-serial-btn-filter-tx-text", label: "串口-按钮-过滤-TX-文本", labelEn: "TX filter button text" },
      {
        var: "--st-serial-btn-filter-tx-active-text",
        label: "过滤TX按钮激活文本",
        labelEn: "TX filter active text",
      },
      { var: "--st-serial-btn-filter-rx-bg", label: "串口-按钮-过滤-RX-背景", labelEn: "RX filter button bg" },
      {
        var: "--st-serial-btn-filter-rx-active-bg",
        label: "过滤RX按钮激活态背景",
        labelEn: "RX filter active bg",
      },
      { var: "--st-serial-btn-filter-rx-text", label: "串口-按钮-过滤-RX-文本", labelEn: "RX filter button text" },
      {
        var: "--st-serial-btn-filter-rx-active-text",
        label: "过滤RX按钮激活文本",
        labelEn: "RX filter active text",
      },

      { var: "--st-serial-view-group-bg", label: "串口-视图-group-背景", labelEn: "View group background" },
      { var: "--st-serial-view-group-border", label: "串口-视图-group-边框", labelEn: "View group border" },
      { var: "--st-serial-btn-view-bg", label: "串口-按钮-视图-背景", labelEn: "View button background" },
      { var: "--st-serial-btn-view-active-bg", label: "串口-按钮-视图-激活-背景", labelEn: "View button active bg" },
      { var: "--st-serial-btn-view-text", label: "串口-按钮-视图-文本", labelEn: "View button text" },
      { var: "--st-serial-btn-view-active-text", label: "串口-按钮-视图-激活-文本", labelEn: "View button active text" },

      { var: "--st-serial-btn-options-bg", label: "串口-按钮-选项-背景", labelEn: "Options button background" },
      { var: "--st-serial-btn-options-hover-bg", label: "串口-按钮-选项-悬停-背景", labelEn: "Options button hover" },
      { var: "--st-serial-btn-options-text", label: "串口-按钮-选项-文本", labelEn: "Options button text" },
      { var: "--st-serial-btn-autoscroll-bg", label: "串口-按钮-自滚-背景", labelEn: "Auto-scroll button bg" },
      {
        var: "--st-serial-btn-autoscroll-active-bg",
        label: "自动滚动按钮激活背景",
        labelEn: "Auto-scroll active bg",
      },

      { var: "--st-serial-btn-clear-bg", label: "串口-按钮-清除-背景", labelEn: "Clear button background" },
      { var: "--st-monitor-toolbar-bg", label: "监视器-工具栏-背景", labelEn: "Monitor toolbar bg" },
      { var: "--st-monitor-divider", label: "监视器-分隔线", labelEn: "Divider" },
      { var: "--st-monitor-empty-text", label: "监视器-空态-文本", labelEn: "Empty state text" },
      { var: "--st-monitor-btn-text", label: "监视器-按钮-文本", labelEn: "Button text" },
      { var: "--st-monitor-btn-autoscroll-active-bg", label: "监视器-按钮-自滚-激活-背景", labelEn: "Autoscroll active bg" },
      { var: "--st-monitor-btn-autoscroll-active-text", label: "监视器-按钮-自滚-激活-文本", labelEn: "Autoscroll active text" },
      { var: "--st-monitor-btn-export-bg", label: "监视器-按钮-导出-背景", labelEn: "Export button bg" },
      { var: "--st-monitor-btn-filter-rx-active-bg", label: "监视器-按钮-过滤-RX-激活-背景", labelEn: "RX filter active bg" },
      { var: "--st-monitor-btn-filter-rx-active-text", label: "监视器-按钮-过滤-RX-激活-文本", labelEn: "RX filter active text" },
      { var: "--st-monitor-btn-filter-tx-active-bg", label: "监视器-按钮-过滤-TX-激活-背景", labelEn: "TX filter active bg" },
      { var: "--st-monitor-btn-filter-tx-active-text", label: "监视器-按钮-过滤-TX-激活-文本", labelEn: "TX filter active text" },
      { var: "--st-monitor-btn-target-physical-active-bg", label: "监视器-按钮-target-物理口-激活-背景", labelEn: "Physical target active" },
      { var: "--st-monitor-btn-target-virtual-active-bg", label: "监视器-按钮-target-虚拟口-激活-背景", labelEn: "Virtual target active" },
      { var: "--st-monitor-btn-view-hex-active-bg", label: "监视器-按钮-视图-HEX-激活-背景", labelEn: "HEX view active" },
      { var: "--st-monitor-btn-view-txt-active-bg", label: "监视器-按钮-视图-TXT-激活-背景", labelEn: "TXT view active" },
      { var: "--st-monitor-config-label", label: "监视器-配置-标签", labelEn: "Config label" },
      { var: "--st-monitor-config-text", label: "监视器-配置-文本", labelEn: "Config text" },
      { var: "--st-monitor-tab-active-text", label: "监视器-标签页-激活-文本", labelEn: "Active tab text" },
      { var: "--st-monitor-tab-inactive-text", label: "监视器-标签页-inactive-文本", labelEn: "Inactive tab text" },
      { var: "--st-monitor-status-offline", label: "监视器-状态-离线", labelEn: "Offline status" },
      { var: "--st-monitor-status-online", label: "监视器-状态-在线", labelEn: "Online status" },
      { var: "--st-serial-btn-autoscroll-active-text", label: "串口-按钮-自滚-激活-文本", labelEn: "Autoscroll active text" },
      { var: "--st-serial-btn-autoscroll-border", label: "串口-按钮-自滚-边框", labelEn: "Autoscroll border" },
      { var: "--st-serial-btn-autoscroll-hover-bg", label: "串口-按钮-自滚-悬停-背景", labelEn: "Autoscroll hover bg" },
      { var: "--st-serial-btn-autoscroll-icon", label: "串口-按钮-自滚-图标", labelEn: "Autoscroll icon" },
      { var: "--st-serial-btn-clear-border", label: "串口-按钮-清除-边框", labelEn: "Clear border" },
      { var: "--st-serial-btn-clear-hover-bg", label: "串口-按钮-清除-悬停-背景", labelEn: "Clear hover bg" },
      { var: "--st-serial-btn-clear-icon", label: "串口-按钮-清除-图标", labelEn: "Clear icon" },
      { var: "--st-serial-btn-crc-active-bg", label: "串口-按钮-CRC-激活-背景", labelEn: "CRC active bg" },
      { var: "--st-serial-btn-filter-rx-hover-bg", label: "串口-按钮-过滤-RX-悬停-背景", labelEn: "RX filter hover" },
      { var: "--st-serial-btn-filter-tx-hover-bg", label: "串口-按钮-过滤-TX-悬停-背景", labelEn: "TX filter hover" },
      { var: "--st-serial-btn-options-border", label: "串口-按钮-选项-边框", labelEn: "Options border" },
      { var: "--st-serial-btn-view-hover-bg", label: "串口-按钮-视图-悬停-背景", labelEn: "View hover bg" },
      { var: "--st-serial-options-hover-bg", label: "串口-选项-悬停-背景", labelEn: "Options hover bg" },
      { var: "--st-serial-toolbar-divider", label: "串口-工具栏-分隔线", labelEn: "Toolbar divider" },
      { var: "--monitor-options-hover-bg", label: "监视器-选项-悬停-背景", labelEn: "Options menu hover" },
      { var: "--monitor-bubble-rx-border", label: "监视器-气泡-RX-边框", labelEn: "RX bubble border" },
      { var: "--monitor-bubble-tx-border", label: "监视器-气泡-TX-边框", labelEn: "TX bubble border" },
      { var: "--st-monitor-log-rx-label-bg", label: "监视器-log-RX-标签-背景", labelEn: "RX log label bg" },
      { var: "--st-monitor-log-tx-label-bg", label: "监视器-log-TX-标签-背景", labelEn: "TX log label bg" },
      { var: "--st-monitor-rx-label-text", label: "监视器-RX-标签-文本", labelEn: "RX label text" },
      { var: "--st-monitor-tx-label-text", label: "监视器-TX-标签-文本", labelEn: "TX label text" },
      { var: "--st-monitor-virtual-label-text", label: "监视器-虚拟口-标签-文本", labelEn: "Virtual label text" },
      { var: "--st-timestamp", label: "时间戳", labelEn: "Timestamp (global)" },
      { var: "--st-monitor-repeat-badge-bg", label: "监视器-重复-徽标-背景", labelEn: "Repeat badge bg" },
      { var: "--st-monitor-repeat-badge-text", label: "监视器-重复-徽标-文本", labelEn: "Repeat badge text" },
      { var: "--st-monitor-gold-flash", label: "监视器-gold-闪烁", labelEn: "New message flash" },
      { var: "--st-monitor-gold-flash-bg", label: "监视器-gold-闪烁-背景", labelEn: "New message flash bg" },
      { var: "--st-monitor-gold-flash-border", label: "监视器-gold-闪烁-边框", labelEn: "New message flash border" },
      { var: "--st-monitor-sys-bg", label: "监视器-全局-背景", labelEn: "System message bg" },
      { var: "--st-monitor-sys-border", label: "监视器-全局-边框", labelEn: "System message border" },
      { var: "--st-monitor-sys-text", label: "监视器-全局-文本", labelEn: "System message text" },
    ],
  },
  "mqtt-monitor": {
    label: "MQTT监视器主区域",
    labelEn: "MQTT Monitor Area",
    tokens: [
      { var: "--st-mqtt-monitor-bg", label: "MQTT-监视器-背景", labelEn: "RX area background" },
      { var: "--st-toolbar-bg", label: "工具栏-背景", labelEn: "Top toolbar background" },
      { var: "--st-mqtt-toolbar-border", label: "MQTT-工具栏-边框", labelEn: "Toolbar border" },

      { var: "--st-mqtt-filter-group-bg", label: "MQTT-过滤-group-背景", labelEn: "Filter group background" },
      { var: "--st-mqtt-filter-group-border", label: "MQTT-过滤-group-边框", labelEn: "Filter group border" },
      { var: "--st-mqtt-filter-group-divider", label: "MQTT-过滤-group-分隔线", labelEn: "Filter group divider" },
      { var: "--st-mqtt-btn-filter-tx-bg", label: "MQTT-按钮-过滤-TX-背景", labelEn: "TX filter button bg" },
      { var: "--st-mqtt-btn-filter-tx-active-bg", label: "MQTT-按钮-过滤-TX-激活-背景", labelEn: "TX filter active bg" },
      { var: "--st-mqtt-btn-filter-tx-text", label: "MQTT-按钮-过滤-TX-文本", labelEn: "TX filter button text" },
      { var: "--st-mqtt-btn-filter-rx-bg", label: "MQTT-按钮-过滤-RX-背景", labelEn: "RX filter button bg" },
      { var: "--st-mqtt-btn-filter-rx-active-bg", label: "MQTT-按钮-过滤-RX-激活-背景", labelEn: "RX filter active bg" },
      { var: "--st-mqtt-btn-filter-rx-text", label: "MQTT-按钮-过滤-RX-文本", labelEn: "RX filter button text" },

      { var: "--st-mqtt-view-group-bg", label: "MQTT-视图-group-背景", labelEn: "View group background" },
      { var: "--st-mqtt-view-group-border", label: "MQTT-视图-group-边框", labelEn: "View group border" },
      { var: "--st-mqtt-btn-view-bg", label: "MQTT-按钮-视图-背景", labelEn: "View button background" },
      { var: "--st-mqtt-btn-view-active-bg", label: "MQTT-按钮-视图-激活-背景", labelEn: "View button active bg" },

      { var: "--st-mqtt-btn-options-bg", label: "MQTT-按钮-选项-背景", labelEn: "Options button background" },
      { var: "--st-mqtt-btn-options-text", label: "MQTT-按钮-选项-文本", labelEn: "Options button text" },
      { var: "--st-mqtt-btn-autoscroll-bg", label: "MQTT-按钮-自滚-背景", labelEn: "Auto-scroll button bg" },
      { var: "--st-mqtt-btn-clear-bg", label: "MQTT-按钮-清除-背景", labelEn: "Clear button background" },

      { var: "--st-mqtt-topic-selected-text", label: "MQTT-主题-选中-文本", labelEn: "Topic selected text" },
      { var: "--st-mqtt-topic-default-tx-color", label: "MQTT-主题-默认-TX-颜色", labelEn: "Default TX topic color" },
      { var: "--st-mqtt-topic-default-rx-color", label: "MQTT-主题-默认-RX-颜色", labelEn: "Default RX topic color" },
      { var: "--st-mqtt-toolbar-bg", label: "MQTT-工具栏-背景", labelEn: "MQTT toolbar bg" },
      { var: "--st-mqtt-toolbar-divider", label: "MQTT-工具栏-分隔线", labelEn: "MQTT toolbar divider" },
      { var: "--st-mqtt-btn-autoscroll-active-bg", label: "MQTT-按钮-自滚-激活-背景", labelEn: "Autoscroll active bg" },
      { var: "--st-mqtt-btn-autoscroll-active-text", label: "MQTT-按钮-自滚-激活-文本", labelEn: "Autoscroll active text" },
      { var: "--st-mqtt-btn-autoscroll-border", label: "MQTT-按钮-自滚-边框", labelEn: "Autoscroll border" },
      { var: "--st-mqtt-btn-autoscroll-hover-bg", label: "MQTT-按钮-自滚-悬停-背景", labelEn: "Autoscroll hover bg" },
      { var: "--st-mqtt-btn-autoscroll-icon", label: "MQTT-按钮-自滚-图标", labelEn: "Autoscroll icon" },
      { var: "--st-mqtt-btn-clear-border", label: "MQTT-按钮-清除-边框", labelEn: "Clear border" },
      { var: "--st-mqtt-btn-clear-hover-bg", label: "MQTT-按钮-清除-悬停-背景", labelEn: "Clear hover bg" },
      { var: "--st-mqtt-btn-clear-icon", label: "MQTT-按钮-清除-图标", labelEn: "Clear icon" },
      { var: "--st-mqtt-btn-filter-rx-active-text", label: "MQTT-按钮-过滤-RX-激活-文本", labelEn: "RX filter active text" },
      { var: "--st-mqtt-btn-filter-rx-hover-bg", label: "MQTT-按钮-过滤-RX-悬停-背景", labelEn: "RX filter hover" },
      { var: "--st-mqtt-btn-filter-tx-active-text", label: "MQTT-按钮-过滤-TX-激活-文本", labelEn: "TX filter active text" },
      { var: "--st-mqtt-btn-filter-tx-hover-bg", label: "MQTT-按钮-过滤-TX-悬停-背景", labelEn: "TX filter hover" },
      { var: "--st-mqtt-btn-options-border", label: "MQTT-按钮-选项-边框", labelEn: "Options border" },
      { var: "--st-mqtt-btn-send-bg", label: "MQTT-按钮-发送-背景", labelEn: "Send button bg" },
      { var: "--st-mqtt-btn-view-active-text", label: "MQTT-按钮-视图-激活-文本", labelEn: "View active text" },
      { var: "--st-mqtt-btn-view-hover-bg", label: "MQTT-按钮-视图-悬停-背景", labelEn: "View hover bg" },
      { var: "--st-mqtt-btn-view-text", label: "MQTT-按钮-视图-文本", labelEn: "View button text" },
      { var: "--st-mqtt-options-hover-bg", label: "MQTT-选项-悬停-背景", labelEn: "MQTT options hover" },
    ],
  },
  "monitor-terminal": {
    label: "虚拟终端控件",
    labelEn: "Virtual Terminal Widget",
    tokens: [
      { var: "--monitor-terminal-bg", label: "监视器-终端-背景", labelEn: "Main background" },
      { var: "--monitor-terminal-toolbar-bg", label: "监视器-终端-工具栏-背景", labelEn: "Toolbar background" },
      { var: "--monitor-terminal-toolbar-border", label: "监视器-终端-工具栏-边框", labelEn: "Toolbar border" },
      { var: "--monitor-terminal-toolbar-text", label: "监视器-终端-工具栏-文本", labelEn: "Toolbar text" },
    ],
  },
  "serial-input": {
    label: "发送区域",
    labelEn: "Send Area",
    tokens: [
      { var: "--st-sendarea-bg", label: "发送区-背景", labelEn: "Send area frame background" },
      { var: "--input-background", label: "输入区-背景", labelEn: "Input background" },
      { var: "--input-foreground", label: "输入区-文本", labelEn: "Input text color" },
      { var: "--input-border-color", label: "输入区-边框-颜色", labelEn: "Input border" },
      { var: "--input-focus-border-color", label: "输入区-焦点-边框-颜色", labelEn: "Input focus border" },
      { var: "--st-btn-switch-active-bg", label: "按钮-开关-激活-背景", labelEn: "Mode switch active" },
      { var: "--st-btn-send-bg", label: "按钮-发送-背景", labelEn: "Send button accent" },
      { var: "--st-sendarea-toolbar-bg", label: "发送区-工具栏-背景", labelEn: "Send toolbar background" },
      { var: "--st-sendarea-toolbar-border", label: "发送区-工具栏-边框", labelEn: "Send toolbar border" },
      { var: "--st-sendarea-toolbar-active", label: "发送区-工具栏-激活", labelEn: "Shortcut key active" },
      { var: "--serial-input-mode-active-bg", label: "串口-输入区-模式-激活-背景", labelEn: "Mode active bg" },
      { var: "--serial-input-mode-active-text", label: "串口-输入区-模式-激活-文本", labelEn: "Mode active text" },
      { var: "--serial-input-toolbar-bg", label: "串口-输入区-工具栏-背景", labelEn: "Input toolbar bg" },
      { var: "--serial-input-toolbar-border", label: "串口-输入区-工具栏-边框", labelEn: "Input toolbar border" },
      { var: "--serial-input-toolbar-text", label: "串口-输入区-工具栏-文本", labelEn: "Input toolbar text" },
      { var: "--st-input-bg", label: "输入区-背景", labelEn: "Input area bg" },
      { var: "--st-input-border", label: "输入区-边框", labelEn: "Input area border" },
      { var: "--st-input-text", label: "输入区-文本", labelEn: "Input text" },
      { var: "--st-input-focus-border", label: "输入区-焦点-边框", labelEn: "Input focus border" },
      { var: "--st-input-btn-text", label: "输入区-按钮-文本", labelEn: "Input button text" },
      { var: "--st-input-btn-send-bg", label: "输入区-按钮-发送-背景", labelEn: "Send button bg" },
      { var: "--st-input-btn-mode-hex-active-bg", label: "输入区-按钮-模式-HEX-激活-背景", labelEn: "HEX mode active bg" },
      { var: "--st-input-btn-mode-hex-active-text", label: "输入区-按钮-模式-HEX-激活-文本", labelEn: "HEX mode active text" },
      { var: "--st-input-btn-mode-txt-active-bg", label: "输入区-按钮-模式-TXT-激活-背景", labelEn: "TXT mode active bg" },
      { var: "--st-input-btn-mode-txt-active-text", label: "输入区-按钮-模式-TXT-激活-文本", labelEn: "TXT mode active text" },
      { var: "--st-input-btn-timer-active-bg", label: "输入区-按钮-定时-激活-背景", labelEn: "Timer active bg" },
      { var: "--st-input-btn-timer-active-text", label: "输入区-按钮-定时-激活-文本", labelEn: "Timer active text" },
      { var: "--st-timer-input-bg", label: "定时器-输入框-背景", labelEn: "Timer input background" },
      { var: "--st-timer-input-border", label: "定时器-输入框-边框", labelEn: "Timer input border" },
      { var: "--st-timer-input-text", label: "定时器-输入框-文本", labelEn: "Timer input text" },
      { var: "--st-timer-input-focus-border", label: "定时器-输入框-焦点边框", labelEn: "Timer input focus border" },
      { var: "--st-input-timer-unit-text", label: "输入区-定时-单位-文本", labelEn: "Timer unit text" },
    ],
  },
  "monitor-bubble": {
    label: "通讯气泡",
    labelEn: "Monitor Message Bubble",
    tokens: [
      { var: "--st-msg-bubble-border", label: "消息-气泡-边框", labelEn: "Bubble base border" },
      { var: "--st-rx-bg", label: "RX-背景", labelEn: "RX bubble background" },
      { var: "--st-tx-bg", label: "TX-背景", labelEn: "TX bubble background" },
      { var: "--st-rx-text", label: "RX-文本", labelEn: "RX bubble text" },
      { var: "--st-tx-text", label: "TX-文本", labelEn: "TX bubble text" },
      { var: "--st-error-text", label: "错误-文本", labelEn: "Error bubble text" },
      { var: "--st-info-text", label: "信息-文本", labelEn: "Info text" },

      { var: "--monitor-rx-label-bg", label: "监视器-RX-标签-背景", labelEn: "RX label badge bg" },
      { var: "--monitor-rx-label-border", label: "监视器-RX-标签-边框", labelEn: "RX label badge border" },
      { var: "--monitor-tx-label-bg", label: "监视器-TX-标签-背景", labelEn: "TX label badge bg" },
      { var: "--monitor-tx-label-border", label: "监视器-TX-标签-边框", labelEn: "TX label badge border" },

      { var: "--st-monitor-timestamp", label: "监视器-时间戳", labelEn: "Timestamp color" },
      { var: "--st-monitor-tag-bg", label: "监视器-标签-背景", labelEn: "Extra tag background" },
      { var: "--st-monitor-tag-text", label: "监视器-标签-文本", labelEn: "Extra tag text" },
      { var: "--st-monitor-tag-border", label: "监视器-标签-边框", labelEn: "Extra tag border" },

      { var: "--st-ctrl-char-fg", label: "控制符-字符-fg", labelEn: "Control char text" },
      { var: "--st-ctrl-char-bg", label: "控制符-字符-背景", labelEn: "Control char background" },
      { var: "--st-ctrl-char-border", label: "控制符-字符-边框", labelEn: "Control char border" },

      { var: "--st-tcom-v-bg", label: "Tcom-v-背景", labelEn: "Tcom → virtual port bg" },
      { var: "--st-tcom-v-border", label: "Tcom-v-边框", labelEn: "Tcom → virtual port border" },
      { var: "--st-tcom-v-text", label: "Tcom-v-文本", labelEn: "Tcom → virtual port badge text" },
      { var: "--st-tcom-v-msg-text", label: "Tcom-v-消息-文本", labelEn: "Tcom → virtual port message" },

      { var: "--st-tcom-p-bg", label: "Tcom-p-背景", labelEn: "Tcom → physical port bg" },
      { var: "--st-tcom-p-border", label: "Tcom-p-边框", labelEn: "Tcom → physical port border" },
      { var: "--st-tcom-p-text", label: "Tcom-p-文本", labelEn: "Tcom → physical port badge text" },
      { var: "--st-tcom-p-msg-text", label: "Tcom-p-消息-文本", labelEn: "Tcom → physical port message" },
    ],
  },

  // ====================================================
  // === 系统消息节点 ===
  // ====================================================
  "system-message": {
    label: "系统消息",
    labelEn: "System Message Bubble",
    tokens: [
      { var: "--sys-msg-default-text", label: "全局-消息-默认-文本", labelEn: "Default status text" },
      { var: "--sys-msg-default-border", label: "全局-消息-默认-边框", labelEn: "Default status border" },
      { var: "--sys-msg-default-bg", label: "全局-消息-默认-背景", labelEn: "Default status background" },
      { var: "--sys-msg-connected-text", label: "全局-消息-已连接-文本", labelEn: "Connected text" },
      { var: "--sys-msg-connected-border", label: "全局-消息-已连接-边框", labelEn: "Connected border" },
      { var: "--sys-msg-connected-bg", label: "全局-消息-已连接-背景", labelEn: "Connected background" },
      { var: "--sys-msg-error-text", label: "全局-消息-错误-文本", labelEn: "Error text" },
      { var: "--sys-msg-error-border", label: "全局-消息-错误-边框", labelEn: "Error border" },
      { var: "--sys-msg-error-bg", label: "全局-消息-错误-背景", labelEn: "Error background" },
      { var: "--sys-msg-bridge-text", label: "全局-消息-桥接-文本", labelEn: "Bridge text" },
      { var: "--sys-msg-bridge-border", label: "全局-消息-桥接-边框", labelEn: "Bridge border" },
      { var: "--sys-msg-bridge-bg", label: "全局-消息-桥接-背景", labelEn: "Bridge background" },
      { var: "--sys-msg-device-text", label: "全局-消息-设备-文本", labelEn: "Device text" },
      { var: "--sys-msg-device-border", label: "全局-消息-设备-边框", labelEn: "Device border" },
      { var: "--sys-msg-device-bg", label: "全局-消息-设备-背景", labelEn: "Device background" },
    ],
  },

  // ====================================================
  // === 各类专属设置侧栏 ===
  // ====================================================
  "serial-config": {
    label: "串口偏好配置面板",
    labelEn: "Serial Config Panel",
    tokens: [
      { var: "--serial-config-bg", label: "串口-配置-背景", labelEn: "Panel background" },
      { var: "--serial-config-text", label: "串口-配置-文本", labelEn: "Config text" },
      { var: "--serial-config-label", label: "串口-配置-标签", labelEn: "Form label color" },
      { var: "--st-config-item-bg", label: "配置-选项-背景", labelEn: "Config item bg" },
      { var: "--st-config-muted-text", label: "配置-弱化-文本", labelEn: "Config muted text" },
      { var: "--st-config-success-text", label: "配置-成功-文本", labelEn: "Config success text" },
      { var: "--st-config-title-text", label: "配置-标题-文本", labelEn: "Config title text" },
    ],
  },
  "mqtt-config": {
    label: "MQTT偏好配置面板",
    labelEn: "MQTT Config Panel",
    tokens: [
      { var: "--mqtt-config-bg", label: "MQTT-配置-背景", labelEn: "Panel background" },
      { var: "--mqtt-config-text", label: "MQTT-配置-文本", labelEn: "Main text color" },
      { var: "--mqtt-config-input-bg", label: "MQTT-配置-输入区-背景", labelEn: "Input background" },
      { var: "--mqtt-config-input-text", label: "MQTT-配置-输入区-文本", labelEn: "Input text color" },
      { var: "--st-config-success-bg", label: "配置-成功-背景", labelEn: "Success/ready indicator" },
      { var: "--mqtt-config-success-bg", label: "MQTT-配置-成功-背景", labelEn: "MQTT success bg" },
    ],
  },
  "command-sidebar": {
    label: "指令集管理器",
    labelEn: "Command Manager",
    tokens: [
      { var: "--command-sidebar-bg", label: "指令-侧栏-背景", labelEn: "Sidebar background" },
      { var: "--command-sidebar-text", label: "指令-侧栏-文本", labelEn: "Normal text color" },
      { var: "--command-sidebar-border", label: "指令-侧栏-边框", labelEn: "Border color" },
      { var: "--st-command-empty-text", label: "指令-空态-文本", labelEn: "Empty state text" },
      { var: "--st-command-drop-indicator", label: "指令-拖拽-指示器", labelEn: "Drag target indicator" },
      { var: "--command-sidebar-drop-indicator", label: "指令-侧栏-拖拽-指示器", labelEn: "Drop indicator" },
      { var: "--command-sidebar-empty-text", label: "指令-侧栏-空态-文本", labelEn: "Empty text" },
    ],
  },
  "module-manager-sidebar": {
    label: "模块管理器侧栏",
    labelEn: "Module Manager Sidebar",
    tokens: [
      { var: "--module-manager-bg", label: "模块-manager-背景", labelEn: "Background" },
      { var: "--module-manager-text", label: "模块-manager-文本", labelEn: "Text color" },
      { var: "--module-manager-border", label: "模块-manager-边框", labelEn: "Border color" },
      { var: "--module-manager-item-hover", label: "模块-manager-选项-悬停", labelEn: "Item hover background" },
      { var: "--st-extension-active-text", label: "扩展-激活-文本", labelEn: "Active module text" },
      { var: "--st-extension-user-text", label: "扩展-user-文本", labelEn: "User module text" },
      { var: "--st-extension-warning-bg", label: "扩展-警告-背景", labelEn: "Warning bg" },
      { var: "--st-extension-warning-text", label: "扩展-警告-文本", labelEn: "Warning text" },
      { var: "--st-extension-danger-hover", label: "扩展-危险-悬停", labelEn: "Danger hover" },
    ],
  },
  "settings-editor": {
    label: "全局设置中心",
    labelEn: "Settings Editor",
    tokens: [
      { var: "--settings-editor-bg", label: "设置-编辑器-背景", labelEn: "Editor background" },
      { var: "--settings-header-background", label: "设置-头部-背景", labelEn: "Header navigation bg" },
      { var: "--st-settings-title-text", label: "设置-标题-文本", labelEn: "Section title text" },
      { var: "--st-settings-text", label: "设置-文本", labelEn: "Settings item text" },
      { var: "--st-settings-danger-title", label: "设置-危险-标题", labelEn: "Danger section title" },
      { var: "--st-settings-danger-text", label: "设置-危险-文本", labelEn: "Danger section text" },
      { var: "--st-settings-danger-bg", label: "设置-危险-背景", labelEn: "Danger item background" },
      { var: "--settings-editor-text", label: "设置-编辑器-文本", labelEn: "Settings text" },
      { var: "--settings-editor-title-text", label: "设置-编辑器-标题-文本", labelEn: "Settings title" },
      { var: "--settings-editor-toolbar-bg", label: "设置-编辑器-工具栏-背景", labelEn: "Settings toolbar bg" },
      { var: "--settings-editor-danger-bg", label: "设置-编辑器-危险-背景", labelEn: "Settings danger bg" },
      { var: "--settings-row-hover-background", label: "设置-行-悬停-背景", labelEn: "Row hover bg" },
      { var: "--st-settings-btn-cancel-hover", label: "设置-按钮-取消-悬停", labelEn: "Cancel hover" },
      { var: "--st-settings-btn-disabled-bg", label: "设置-按钮-禁用-背景", labelEn: "Disabled button bg" },
      { var: "--st-settings-btn-disabled-text", label: "设置-按钮-禁用-文本", labelEn: "Disabled button text" },
      { var: "--st-settings-danger-bg-subtle", label: "设置-危险-背景-淡色", labelEn: "Danger subtle bg" },
      { var: "--st-settings-danger-hover", label: "设置-危险-悬停", labelEn: "Danger hover" },
      { var: "--st-settings-footer-bg", label: "设置-底部-背景", labelEn: "Footer bg" },
      { var: "--st-settings-footer-border", label: "设置-底部-边框", labelEn: "Footer border" },
      { var: "--st-settings-text-hover", label: "设置-文本-悬停", labelEn: "Text hover" },
    ],
  },
  "graph-editor": {
    label: "桥接流图编辑器",
    labelEn: "Graph Flow Editor",
    tokens: [
      { var: "--st-graph-canvas-bg", label: "流图-画布-背景", labelEn: "Infinite canvas bg" },
      { var: "--st-graph-toolbar-bg", label: "流图-工具栏-背景", labelEn: "Toolbar background" },
      { var: "--st-graph-node-title", label: "流图-节点-标题", labelEn: "Node card title" },
      { var: "--st-graph-subnode-bg", label: "流图-子节点-背景", labelEn: "Sub-node inner bg" },
      { var: "--st-graph-subnode-border", label: "流图-子节点-边框", labelEn: "Sub-node border" },
      { var: "--st-graph-port-border", label: "流图-端口-边框", labelEn: "Port connector border" },
      { var: "--st-graph-port-hover-bg", label: "流图-端口-悬停-背景", labelEn: "Port connector hover bg" },
      { var: "--st-graph-divider", label: "流图-分隔线", labelEn: "Graph divider" },
      { var: "--st-graph-icon-bus", label: "流图-图标-总线", labelEn: "Bus icon color" },
      { var: "--st-graph-icon-pair", label: "流图-图标-配对", labelEn: "Pair icon color" },
      { var: "--st-graph-icon-physical", label: "流图-图标-物理口", labelEn: "Physical icon" },
      { var: "--st-graph-icon-virtual", label: "流图-图标-虚拟口", labelEn: "Virtual icon" },
      { var: "--st-graph-port-hover-border", label: "流图-端口-悬停-边框", labelEn: "Port hover border" },
      { var: "--st-graph-toolbar-border", label: "流图-工具栏-边框", labelEn: "Toolbar border" },
    ],
  },

  // ====================================================
  // === Globals (全局基址与公共小件) ===
  // ====================================================
  "global-common": {
    label: "全局基础色",
    labelEn: "Global Common",
    tokens: [
      { var: "--app-background", label: "全局-背景", labelEn: "App global background" },
      { var: "--app-foreground", label: "全局-文本", labelEn: "App global foreground" },
      { var: "--border-color", label: "边框-颜色", labelEn: "Global border color" },
      { var: "--widget-border-color", label: "组件-边框-颜色", labelEn: "Widget border color" },
      { var: "--accent-color", label: "强调-颜色", labelEn: "Accent color (selection/indicator)" },
      { var: "--focus-border-color", label: "焦点-边框-颜色", labelEn: "Focus border color" },
      { var: "--hover-background", label: "悬停-背景", labelEn: "Hover background" },
      { var: "--selection-background", label: "选区-背景", labelEn: "Selection background" },
      { var: "--panel-background", label: "面板-背景", labelEn: "Panel background" },
      { var: "--widget-background", label: "组件-背景", labelEn: "Widget background" },
      { var: "--link-foreground", label: "链接-文本", labelEn: "Link text color" },
      { var: "--st-accent", label: "强调", labelEn: "Accent helper" },
      { var: "--st-widget-border", label: "组件-边框", labelEn: "Widget border" },
      { var: "--sys-color-primary-dark", label: "全局-颜色-主要-dark", labelEn: "Primary dark" },
    ],
  },
  "global-components": {
    label: "表单控件",
    labelEn: "Form Controls",
    tokens: [
      { var: "--input-background", label: "输入区-背景", labelEn: "Input background" },
      { var: "--input-foreground", label: "输入区-文本", labelEn: "Input text color" },
      { var: "--input-border-color", label: "输入区-边框-颜色", labelEn: "Input border" },
      { var: "--input-placeholder-color", label: "输入区-占位-颜色", labelEn: "Placeholder text color" },
      { var: "--checkbox-background", label: "复选框-背景", labelEn: "Checkbox background" },
      { var: "--checkbox-foreground", label: "复选框-文本", labelEn: "Checkbox check mark" },
      { var: "--st-dropdown-bg", label: "下拉-背景", labelEn: "Dropdown container bg" },
      { var: "--st-btn-primary-bg", label: "按钮-主要-背景", labelEn: "Primary action button bg" },
      { var: "--st-btn-secondary-bg", label: "按钮-次要-背景", labelEn: "Secondary action button bg" },
      { var: "--switch-active-bg", label: "开关-激活-背景", labelEn: "Switch active accent" },
      { var: "--dropdown-background", label: "下拉-背景", labelEn: "Dropdown background" },
      { var: "--dropdown-border-color", label: "下拉-边框-颜色", labelEn: "Dropdown border" },
      { var: "--dropdown-item-hover-background", label: "下拉-选项-悬停-背景", labelEn: "Dropdown item hover" },
      { var: "--dropdown-item-selected-foreground", label: "下拉-选项-选中-文本", labelEn: "Dropdown item selected" },
      { var: "--checkbox-border-color", label: "复选框-边框-颜色", labelEn: "Checkbox border" },
      { var: "--st-switch-text-hover", label: "开关-文本-悬停", labelEn: "Switch hover text" },
    ],
  },
  "custom-select": {
    label: "自定义选择器",
    labelEn: "Custom Select",
    tokens: [
      { var: "--st-select-bg", label: "选择器-背景", labelEn: "Select list background" },
      { var: "--st-select-border", label: "选择器-边框", labelEn: "Select border" },
      { var: "--st-select-text", label: "选择器-文本", labelEn: "Normal text" },
      { var: "--st-select-hover", label: "选择器-悬停", labelEn: "Hover highlight" },
      { var: "--st-select-selected", label: "选择器-选中", labelEn: "Selected accent" },
    ]
  },
  "log-search": {
    label: "日志搜索",
    labelEn: "Log Search",
    tokens: [
      { var: "--st-logsearch-bg", label: "搜索-背景", labelEn: "Search bar background" },
      { var: "--st-logsearch-border", label: "搜索-边框", labelEn: "Outer border" },
      { var: "--st-logsearch-text", label: "搜索-文本", labelEn: "Query text color" },
      { var: "--st-logsearch-match-highlight", label: "搜索-match-highlight", labelEn: "Match highlight color" },
    ]
  },
  "global-scrollbar": {
    label: "全局滚动条样式",
    labelEn: "Global Scrollbar",
    tokens: [
      { var: "--scrollbar-shadow-color", label: "滚动条-阴影-颜色", labelEn: "Scrollbar track shadow" },
      { var: "--scrollbar-slider-color", label: "滚动条-滑块-颜色", labelEn: "Scrollbar thumb color" },
      { var: "--scrollbar-slider-hover-color", label: "滚动条-滑块-悬停-颜色", labelEn: "Scrollbar thumb hover" },
      { var: "--scrollbar-slider-active-color", label: "滚动条-滑块-激活-颜色", labelEn: "Scrollbar thumb active" },
      { var: "--st-select-item-text", label: "选择器-选项-文本", labelEn: "Item text" },
      { var: "--st-search-text", label: "search-文本", labelEn: "Search text color" },
    ],
  },
  "context-menu": {
    label: "右键菜单",
    labelEn: "Context Menu",
    tokens: [
      { var: "--context-menu-bg", label: "右键菜单-菜单-背景", labelEn: "Menu background" },
      { var: "--context-menu-border", label: "右键菜单-菜单-边框", labelEn: "Menu border" },
      { var: "--context-menu-text", label: "右键菜单-菜单-文本", labelEn: "Menu item text" },
      { var: "--context-menu-item-hover", label: "右键菜单-菜单-选项-悬停", labelEn: "Item hover background" },
      { var: "--context-menu-hover-bg", label: "右键菜单-菜单-悬停-背景", labelEn: "Item hover bg" },
      { var: "--st-contextmenu-text-hover", label: "contextmenu-文本-悬停", labelEn: "Item hover text" },
    ],
  },
  dialog: {
    label: "弹窗与对话确认框",
    labelEn: "Dialog & Confirm",
    tokens: [
      { var: "--st-dialog-header-bg", label: "对话框-头部-背景", labelEn: "Header background" },
      { var: "--st-dialog-content-bg", label: "对话框-内容-背景", labelEn: "Content background" },
      { var: "--st-dialog-footer-bg", label: "对话框-底部-背景", labelEn: "Footer background" },
      { var: "--st-dialog-text", label: "对话框-文本", labelEn: "Body text" },
      { var: "--st-dialog-muted-text", label: "对话框-弱化-文本", labelEn: "Muted text" },
      { var: "--st-dialog-border", label: "对话框-边框", labelEn: "Dialog border" },
      { var: "--st-dialog-icon-hover", label: "对话框-图标-悬停", labelEn: "Close icon hover" },
    ],
  },
  tooltip: {
    label: "提示框",
    labelEn: "Tooltip",
    tokens: [
      { var: "--st-tooltip-bg", label: "提示-背景", labelEn: "Dark inverse background" },
      { var: "--st-tooltip-text", label: "提示-文本", labelEn: "Tooltip text" },
      { var: "--st-tooltip-border", label: "提示-边框", labelEn: "Border" },
    ],
  },
  toast: {
    label: "通知消息",
    labelEn: "Toast Notification",
    tokens: [
      { var: "--st-toast-text", label: "通知-文本", labelEn: "Toast message text" },
      { var: "--st-toast-icon-hover", label: "通知-图标-悬停", labelEn: "Interactive icon" },
      { var: "--st-toast-bg", label: "通知-背景", labelEn: "Toast background" },
      { var: "--st-toast-border", label: "通知-边框", labelEn: "Toast border" },
    ],
  },
  "st-status-indicators": {
    label: "状态指示灯",
    labelEn: "Status Indicators",
    tokens: [
      { var: "--st-status-success", label: "状态-成功", labelEn: "Success / online / ready" },
      { var: "--st-status-error", label: "状态-错误", labelEn: "Error / offline / occupied" },
      { var: "--st-status-success-bg", label: "状态-成功-背景", labelEn: "Success bg" },
      { var: "--st-status-error-bg", label: "状态-错误-背景", labelEn: "Error bg" },
      { var: "--st-status-info", label: "状态-信息", labelEn: "Info status" },
      { var: "--st-status-info-bg", label: "状态-信息-背景", labelEn: "Info bg" },
      { var: "--st-status-warning", label: "状态-警告", labelEn: "Warning status" },
      { var: "--st-status-warning-bg", label: "状态-警告-背景", labelEn: "Warning bg" },
      { var: "--st-status-danger-text", label: "状态-危险-文本", labelEn: "Danger text" },
    ],
  },

  "virtual-port-plugin": {
    label: "虚拟串口插件面板",
    labelEn: "Virtual Port Plugin Panel",
    tokens: [
      { var: "--st-vport-alert-bg", label: "虚拟口-警告框-背景", labelEn: "Alert background" },
      { var: "--st-vport-alert-border", label: "虚拟口-警告框-边框", labelEn: "Alert border" },
      { var: "--st-vport-alert-text", label: "虚拟口-警告框-文本", labelEn: "Alert text" },
    ],
  },
  "st-connection-control": {
    label: "监听连接控制区",
    labelEn: "Connection Control",
    tokens: [
      { var: "--st-conn-start-bg", label: "连接-启动-背景", labelEn: "Start button background" },
      { var: "--st-conn-start-hover", label: "连接-启动-悬停", labelEn: "Start button hover" },
      { var: "--st-conn-stop-bg", label: "连接-停止-背景", labelEn: "Stop button background" },
      { var: "--st-conn-stop-hover", label: "连接-停止-悬停", labelEn: "Stop button hover" },
      { var: "--st-conn-disabled-bg", label: "连接-禁用-背景", labelEn: "Disabled state background" },
      { var: "--st-conn-disabled-text", label: "连接-禁用-文本", labelEn: "Disabled state text" },
    ],
  },
  // ====================================================
  // === 新增分组 ===
  // ====================================================
  "button": {
    label: "按钮",
    labelEn: "Button",
    tokens: [
      { var: "--button-background", label: "按钮-背景", labelEn: "Primary button background" },
      { var: "--button-foreground", label: "按钮-文本", labelEn: "Primary button text" },
      { var: "--button-hover-background", label: "按钮-悬停-背景", labelEn: "Primary hover background" },
      { var: "--button-secondary-background", label: "按钮-次要-背景", labelEn: "Secondary background" },
      { var: "--button-secondary-hover-background", label: "按钮-次要-悬停-背景", labelEn: "Secondary hover bg" },
      { var: "--st-btn-primary-hover", label: "按钮-主要-悬停", labelEn: "Primary hover" },
      { var: "--st-btn-primary-text", label: "按钮-主要-文本", labelEn: "Primary text" },
    ],
  },
  "danger-colors": {
    label: "危险操作色",
    labelEn: "Danger Colors",
    tokens: [
      { var: "--st-danger-bg", label: "危险-背景", labelEn: "Danger button background" },
      { var: "--st-danger-hover-bg", label: "危险-悬停-背景", labelEn: "Danger button hover" },
      { var: "--st-danger-text", label: "危险-文本", labelEn: "Danger button text" },
    ],
  },
  "list-select": {
    label: "列表与选区",
    labelEn: "List & Selection",
    tokens: [
      { var: "--list-hover-background", label: "列表-悬停-背景", labelEn: "List hover background" },
      { var: "--list-active-background", label: "列表-激活-背景", labelEn: "List active background" },
      { var: "--list-active-foreground", label: "列表-激活-文本", labelEn: "List active foreground" },
      { var: "--list-active-selection-background", label: "列表-激活-选区-背景", labelEn: "List active selection bg" },
    ],
  },
  "menu": {
    label: "菜单",
    labelEn: "Menu",
    tokens: [
      { var: "--menu-background", label: "菜单-背景", labelEn: "Menu background" },
      { var: "--menu-foreground", label: "菜单-文本", labelEn: "Menu text" },
      { var: "--menu-border-color", label: "菜单-边框-颜色", labelEn: "Menu border" },
    ],
  },
  "terminal-monitor": {
    label: "终端监视器按钮",
    labelEn: "Terminal Monitor Buttons",
    tokens: [
      { var: "--st-terminal-bg", label: "终端-背景", labelEn: "Terminal background" },
      { var: "--st-ter-toolbar-divider", label: "终端-工具栏-分隔线", labelEn: "Terminal toolbar divider" },
      { var: "--st-ter-filter-group-bg", label: "终端-过滤-group-背景", labelEn: "Terminal filter group bg" },
      { var: "--st-ter-filter-group-border", label: "终端-过滤-group-边框", labelEn: "Ter filter group border" },
      { var: "--st-ter-filter-group-divider", label: "终端-过滤-group-分隔线", labelEn: "Ter filter group divider" },
      { var: "--st-ter-view-group-bg", label: "终端-视图-group-背景", labelEn: "Ter view group bg" },
      { var: "--st-ter-view-group-border", label: "终端-视图-group-边框", labelEn: "Ter view group border" },
      { var: "--st-ter-btn-filter-tx-bg", label: "终端-按钮-过滤-TX-背景", labelEn: "Ter TX filter bg" },
      { var: "--st-ter-btn-filter-tx-hover-bg", label: "终端-按钮-过滤-TX-悬停-背景", labelEn: "Ter TX filter hover" },
      { var: "--st-ter-btn-filter-tx-text", label: "终端-按钮-过滤-TX-文本", labelEn: "Ter TX filter text" },
      { var: "--st-ter-btn-filter-tx-active-text", label: "终端-按钮-过滤-TX-激活-文本", labelEn: "Ter TX filter active" },
      { var: "--st-ter-btn-filter-rx-bg", label: "终端-按钮-过滤-RX-背景", labelEn: "Ter RX filter bg" },
      { var: "--st-ter-btn-filter-rx-hover-bg", label: "终端-按钮-过滤-RX-悬停-背景", labelEn: "Ter RX filter hover" },
      { var: "--st-ter-btn-filter-rx-text", label: "终端-按钮-过滤-RX-文本", labelEn: "Ter RX filter text" },
      { var: "--st-ter-btn-filter-rx-active-text", label: "终端-按钮-过滤-RX-激活-文本", labelEn: "Ter RX filter active" },
      { var: "--st-ter-btn-view-bg", label: "终端-按钮-视图-背景", labelEn: "Ter view button bg" },
      { var: "--st-ter-btn-view-hover-bg", label: "终端-按钮-视图-悬停-背景", labelEn: "Ter view hover bg" },
      { var: "--st-ter-btn-view-text", label: "终端-按钮-视图-文本", labelEn: "Ter view text" },
      { var: "--st-ter-btn-view-active-text", label: "终端-按钮-视图-激活-文本", labelEn: "Ter view active text" },
      { var: "--st-ter-btn-options-bg", label: "终端-按钮-选项-背景", labelEn: "Ter options bg" },
      { var: "--st-ter-btn-options-border", label: "终端-按钮-选项-边框", labelEn: "Ter options border" },
      { var: "--st-ter-btn-options-text", label: "终端-按钮-选项-文本", labelEn: "Ter options text" },
      { var: "--st-ter-btn-autoscroll-bg", label: "终端-按钮-自滚-背景", labelEn: "Ter autoscroll bg" },
      { var: "--st-ter-btn-autoscroll-border", label: "终端-按钮-自滚-边框", labelEn: "Ter autoscroll border" },
      { var: "--st-ter-btn-autoscroll-hover-bg", label: "终端-按钮-自滚-悬停-背景", labelEn: "Ter autoscroll hover" },
      { var: "--st-ter-btn-autoscroll-icon", label: "终端-按钮-自滚-图标", labelEn: "Ter autoscroll icon" },
      { var: "--st-ter-btn-autoscroll-active-text", label: "终端-按钮-自滚-激活-文本", labelEn: "Ter autoscroll active" },
      { var: "--st-ter-btn-clear-bg", label: "终端-按钮-清除-背景", labelEn: "Ter clear bg" },
      { var: "--st-ter-btn-clear-border", label: "终端-按钮-清除-边框", labelEn: "Ter clear border" },
      { var: "--st-ter-btn-clear-hover-bg", label: "终端-按钮-清除-悬停-背景", labelEn: "Ter clear hover" },
      { var: "--st-ter-btn-clear-icon", label: "终端-按钮-清除-图标", labelEn: "Ter clear icon" },
    ],
  },
  "token-colors": {
    label: "Token令牌着色",
    labelEn: "Token Colors",
    tokens: [
      { var: "--st-token-arrow", label: "Token-箭头", labelEn: "Arrow token" },
      { var: "--st-token-arrow-hover", label: "Token-箭头-悬停", labelEn: "Arrow token hover" },
      { var: "--st-token-auto-inc", label: "Token-自增", labelEn: "Auto-increment token" },
      { var: "--st-token-crc", label: "Token-CRC", labelEn: "CRC token" },
      { var: "--st-token-divider", label: "Token-分隔线", labelEn: "Divider token" },
      { var: "--st-token-flag", label: "Token-标记", labelEn: "Flag token" },
      { var: "--st-token-random", label: "Token-随机", labelEn: "Random token" },
      { var: "--st-token-timestamp", label: "Token-时间戳", labelEn: "Timestamp token" },
    ],
  },
  "json-highlight": {
    label: "JSON高亮语法色",
    labelEn: "JSON Syntax Highlight",
    tokens: [
      { var: "--st-json-key", label: "JSON-键名", labelEn: "JSON key" },
      { var: "--st-json-string", label: "JSON-字符串", labelEn: "JSON string" },
      { var: "--st-json-number", label: "JSON-数字", labelEn: "JSON number" },
      { var: "--st-json-boolean", label: "JSON-布尔", labelEn: "JSON boolean" },
      { var: "--st-json-null", label: "JSON-空值", labelEn: "JSON null" },
      { var: "--st-json-punctuation", label: "JSON-标点", labelEn: "JSON punctuation" },
    ],
  },
  "update-panel": {
    label: "自动更新面板",
    labelEn: "Auto Update Panel",
    tokens: [
      { var: "--st-update-btn-bg", label: "更新-按钮-背景", labelEn: "Update button bg" },
      { var: "--st-update-btn-hover", label: "更新-按钮-悬停", labelEn: "Update button hover" },
      { var: "--st-update-btn-text", label: "更新-按钮-文本", labelEn: "Update button text" },
      { var: "--st-update-spinner", label: "更新-加载", labelEn: "Update spinner" },
      { var: "--st-update-text", label: "更新-文本", labelEn: "Update panel text" },
    ],
  },
};
